nodeLinker: node-modules
enableGlobalCache: true
nmMode: hardlinks-local

# Allow lockfile modifications
enableImmutableInstalls: false
enableStrictSsl: false

# Prevent peer dependency issues
enableTransparentWorkspaces: true
enableInlineBuilds: true
enableScripts: true

logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0006
    level: discard
  - code: YN0076
    level: discard 